### ISSUE TITLE
Notifications not working in Chrome 68

### ISSUE THREAD

**Issue by gswood01** [Dellos7/ms-teams-notifications-tampermonkey#1]
I am using Chrome Version 68.0.3440.75 (Official Build) (64-bit) / Ubuntu 16.04 and can't get notifications working. Have you tested on Chrome 68?

**Comment by Dellos7** [comment]
Hello,

I've tested today in Versión 68.0.3440.106 (Build oficial) (64 bits) / Windows 10 and I can get them working.

Have you realizedthat when you install the script / refresh the teams web page it asks you for permissions on notifications?

![https://image.ibb.co/ig5GJ9/teams_notifications.png](https://image.ibb.co/ig5GJ9/teams_notifications.png)

If you close that window or you do not grant notifications, they won't work. 

If this windows never appears, then script is not installed or something is wrong with it.

Would you mind sending here the output in the Google Chrome's console when you reaload the page after you enable or install the script in tampermonkey?

Thank you.

**Comment by gswood01** [comment]
I had refreshed and granted permission, but after I restarted chrome it worked. The only other thing that I can think of was I turned notifications off on my phone and closed teams that was open in a browser on another computer. I think "user error" would be a good resolution to this issue.

Thanks for the help.
